services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-airflow-volume:/var/lib/postgresql/data
    networks:
      - net

  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=destination_db
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - net

  init-airflow:
    image: apache/airflow:latest
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init && 
               airflow users create --username airflow --password pwd --firstname John --lastname Doe --role Admin --email admin@example.com"
    networks:
      - net

  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:latest
  #   # command:
  #   #   [
  #   #     "run",
  #   #     "--profiles-dir",
  #   #     "/root",
  #   #     "--project-dir",
  #   #     "/lesswrong",
  #   #     "--full-refresh"
  #   #   ]
  #   networks:
  #     - net
  #   volumes:
  #     - ./lesswrong:/lesswrong
  #     - ~/.dbt:/root
  #   depends_on:
  #     - destination_postgres
  #     - init-airflow
  #   environment:
  #     DBT_PROFILE: lesswrong
  #     DBT_TARGET: dev

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - init-airflow
      - postgres
      - destination_postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=plIipb9RU3-3wJ1UNaAtqVNJrqFEks1-dGbJM34EW7U=
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=pwd
      - AIRFLOW_WWW_USER_USERNAME=airflow
      - AIRFLOW_WWW_USER_PASSWORD=pwd
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ./lesswrong:/opt/airflow/lesswrong
      - ~/.dbt:/.dbt
    networks:
      - net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - init-airflow
      - postgres
      - destination_postgres
    environment:
      - AWS_PROFILE=lesswrong
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=plIipb9RU3-3wJ1UNaAtqVNJrqFEks1-dGbJM34EW7U=
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=pwd
      - AIRFLOW_WWW_USER_USERNAME=airflow
      - AIRFLOW_WWW_USER_PASSWORD=pwd
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ./lesswrong:/lesswrong
      - ~/.dbt:/root/.dbt
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres-airflow-volume:
  postgres-db-volume: